apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: deploy-from-github-serviceaccount-binding
  namespace: github-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-from-github
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:serviceaccount:github-actions:github-actions-sa
