apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: github-actions-example
  name: github-actions-example
  namespace: github-actions
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: github-actions-example
  type: LoadBalancer
status:
  loadBalancer: {}
